#!/usr/bin/env python3
"""Compose this project's steamos-manager device profile from Valve's.

steamos-manager selects one device profile per machine; it does not merge them.
So a profile of ours that matches the same DMI replaces Valve's outright, and
every section theirs declares has to be present in ours or it is silently lost.
Shipping a hand-copied duplicate makes that a standing promise to notice every
future change Valve makes, and that promise has already been broken once: the
first version carried only [tdp_limit], dropped [inputplumber], and took the
handheld's volume keys with it.

So do not copy by hand. Read Valve's profile at restore time and append the one
section they leave out. Whatever they add later is inherited for free, and if
they ever declare a TDP method themselves this file steps aside completely.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path

UPSTREAM_PROFILE = "usr/share/steamos-manager/devices/msi-claw-intel.toml"
COMPOSED_PROFILE = "usr/share/steamos-manager/devices/99-rivoreo-msi-claw-tdp.toml"

# Kept in step with the clamp range in power_control, which is what the daemon
# will actually honour. Offering Steam a wider slider than the daemon accepts
# would show positions that quietly do nothing.
TDP_MIN_W = 8
TDP_MAX_W = 30

HEADER = """# Generated by steamos-intel-handheld. Do not edit.
#
# This is Valve's msi-claw-intel.toml with a [tdp_limit] section appended.
# steamos-manager picks one profile per device rather than merging them, so the
# whole of Valve's profile has to be repeated here for their settings to
# survive. It is copied at restore time rather than by hand, so anything they
# add later is inherited automatically.
#
# Without the appended section steamos-manager never sets up TDP limiting on
# this board: TdpLimit1 is not exported, and Steam's own performance-menu
# slider does nothing.
#
# Delete this file to return to stock behaviour.
"""

APPENDED = f"""
[tdp_limit]
method = "remote"

[tdp_limit.range]
min = {TDP_MIN_W}
max = {TDP_MAX_W}
"""

_TDP_SECTION = re.compile(r"^\s*\[tdp_limit(\.|])", re.MULTILINE)


@dataclass(frozen=True)
class ProfileDecision:
    """What the composed profile should look like, and why."""

    content: str | None
    reason: str

    @property
    def should_exist(self) -> bool:
        return self.content is not None


def decide(upstream_text: str | None) -> ProfileDecision:
    if upstream_text is None:
        return ProfileDecision(
            None,
            "no upstream MSI Claw profile on this system; nothing to extend",
        )
    if _TDP_SECTION.search(upstream_text):
        return ProfileDecision(
            None,
            "upstream now declares its own tdp_limit; standing aside",
        )
    return ProfileDecision(HEADER + "\n" + upstream_text.rstrip("\n") + "\n" + APPENDED, "composed")


def read_upstream(system_root: Path) -> str | None:
    path = Path(system_root) / UPSTREAM_PROFILE
    try:
        return path.read_text()
    except OSError:
        return None


def compose(system_root: Path) -> ProfileDecision:
    return decide(read_upstream(system_root))


def composed_path(system_root: Path) -> Path:
    return Path(system_root) / COMPOSED_PROFILE


def current_content(system_root: Path) -> str | None:
    try:
        return composed_path(system_root).read_text()
    except OSError:
        return None
